products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products import views
from django.urls import path

urlpatterns = [
    path('panel', views.panel_view),
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product')
]

python_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('welcome.urls')),
    path('', include('users.urls')),
    path('', include('products.urls')),
    path('', include('orders.urls')),


]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path('registration', views.registration),
    path('login', views.login_view),
    path('logout', views.logout_view),
    path('verify-email', views.verify_view)
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return f"{self.name} {self.price}"

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return f"{self.id}"

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/views.py
from django.shortcuts import render
from products.models import *
# Create your views here.
def panel_view(request):
    products_images = ProductImage.objects.filter(is_active = True, is_main = True)
    return render(request, 'panel.html', locals())


def product(request, product_id):
    product = Product.objects.get(id=product_id)


    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)


    return render(request, 'product.html', locals())

products/templates/panel.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

</head>

<body>
{% include 'header.html' with user=user %}
<div class="men-fashions">
	 <div class="container">
		 <div class="col-md-9 fashions">
			 <div class="title">
			 </div>

			 <div class="fashion-section">
					 {% for product_image in products_images %}
					     <div class="col-md-4 fashion-grid">
							 <div class="product-item">
								 <div>
									 <a href="{% url 'product' product_image.product.id %}">
									 <img src="{{product_image.image.url}}" class="img-responsive">
									 </a>
								 </div>
								 <h4>{{product_image.product.name}}</h4>
							 </div>
						 </div>
					 {% endfor %}

			 </div>
		 </div>
		 <div class="clearfix"></div>
	 </div>
</div>
{% include 'footer.html' with user=user %}

</body>
</html>

products/templates/product.html
{% extends 'main.html' %}
{% load static %}



{% block content %}

<div class="single-section">
	 <div class="col-md-8 fashions2">
			<div class="slider2">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
		   </div>
	  </div>
	<div class="col-md-4 side-bar2">
		  <div class="product-price">
			   <div class="product-name">
				 <h2>{{product.name}}</h2>
					<p>{{product.description}}</p>
					<span>{{product.price}} BYN</span>
	                   <div class="clearfix"></div>
			  </div>
              <br>
              {% if user.is_authenticated %}

              <div class="add-to-cart-btn">
                  <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
                      <input type="number" class="form-control" name="number" id="number">

                  <button type = 'submit' id="submit_btn" class="btn btn-success"
                          data-product_id = '{{product.id}}'
                          data-name = '{{product.name}}'
                          data-price ="{{ product.price }}"
                  >
                      Купить
                  </button>
              </div>
                  </form>
              {% endif %}
		 </div>
      </div>

	 <div class="clearfix"></div>
</div>
{% endblock %}